apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
  namespace: default
 ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: flask-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch" ,"update"]
 ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flask-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: flask-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: flask-role
  apiGroup: rbac.authorization.k8s.io   
 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "waiting for mysql...";
                sleep 3;
              done
      serviceAccountName: flask-sa
      containers:
        - name: flask
          image: yg7821/devopsexamapp:v4
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          env:
           - name: FLASK_SECRET_KEY
             valueFrom:
               secretKeyRef:
                 name: flask-secret
                 key: FLASK_SECRET_KEY
             name: MYSQL_PASSWORD
             valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: "512Mi"   # Minimum guaranteed memory
              cpu: "500m"      # Minimum guaranteed CPU (500 millicores / 0.50 vCPU)
            limits:
              memory: "1Gi"   # Hard ceiling for memory
              cpu: "1"      # Hard ceiling for CPU (1000 millicores / 1 vCPU)                  
          readinessProbe:
            tcpSocket:
              port: port
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: port
            initialDelaySeconds: 15
            periodSeconds: 20      
